services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_ai_workspace

    stdin_open: true
    tty: true

    network_mode: "host"
    ipc: host
    pid: host
    gpus: all

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-42}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      FASTDDS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      FASTRTPS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/workspace:rw

  doosan_dev:
    build:
      context: .
      dockerfile: Dockerfile.doosan
    container_name: ros2_doosan_workspace
    profiles:
      - doosan

    stdin_open: true
    tty: true

    network_mode: "host"
    ipc: host
    pid: host
    gpus: all

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-42}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      FASTDDS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      FASTRTPS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:rw

  full_dev:
    build:
      context: .
      dockerfile: Dockerfile.isaac-moveit
    container_name: ros2_full_workspace
    profiles:
      - full

    stdin_open: true
    tty: true

    network_mode: "host"
    ipc: host
    pid: host
    gpus: all

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-42}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      FASTDDS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      FASTRTPS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:rw
