x-build-args: &build-args
  ROS_BASE_IMAGE: "${ROS_BASE_IMAGE:-ros:jazzy-ros-base-noble@sha256:31daab66eef9139933379fb67159449944f4e2dcf2e22c2d12cc715f29873e0f}"
  UV_IMAGE: "${UV_IMAGE:-ghcr.io/astral-sh/uv:0.8.3@sha256:ef11ed817e6a5385c02cd49fdcc99c23d02426088252a8eace6b6e6a2a511f36}"
  DEVELOPER_UID: "${LOCAL_UID:-1000}"
  DEVELOPER_GID: "${LOCAL_GID:-1000}"

x-build: &build
  context: .
  dockerfile: Dockerfile
  args: *build-args

x-non-root-service: &non-root-service
  user: developer
  init: true
  stdin_open: true
  tty: true
  environment:
    ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-42}"
    RMW_IMPLEMENTATION: "${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"
    FASTDDS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
    FASTRTPS_DEFAULT_PROFILES_FILE: /workspace/config/fastdds.xml
  volumes:
    - type: bind
      source: .
      target: /workspace
      bind:
        create_host_path: false

services:
  ros2_dev:
    <<: *non-root-service
    build:
      <<: *build
      target: ros-python-dev

  ai_dev:
    <<: *non-root-service
    profiles:
      - ai
    build:
      <<: *build
      target: ros-ai-dev
